### ISSUE TITLE
Avatar para usuários

### ISSUE THREAD

**Issue by hlmerscher** [hlmerscher/dojo-onde#14]
A ideia é usar o avatar ao invés do nome do usuário na lista de participantes do dojo, fazendo um grid de todas as pessoas que participarão/participaram.

Acredito que seja melhor e mais simples utilizar o gravatar ao invés de fazer um upload
https://en.gravatar.com/site/implement/images/ruby/

**Comment by m3nd3s** [comment]
Ei @hlmerscher, tomei a liberdade de implementar essa feature, queria uma dica sua de como posso fazer o login localhost para testar. Tem algum macete específico?

**Comment by hlmerscher** [comment]
Não tem mistério, é só criar um user via console mesmo:

```ruby
irb> User.create(name: "Hercules", email: "hlmerscher@gmail.com", password: "123456", password_confirmation: "123456")
```

Ainda precisa ser adicionado no arquivo de seeds um usuário genérico apenas para desenvolvimento no arquivo e atualizar no README o passo a passo.

**Comment by m3nd3s** [comment]
@hlmerscher massa, qualquer coisa eu adiciono essa parada também :wink:

**Comment by hlmerscher** [comment]
:+1:

**Comment by m3nd3s** [comment]
@hlmerscher @jvrmaia o que acham? Ficou bacana? :smile: 

![image](https://cloud.githubusercontent.com/assets/287685/10713118/717559a6-7a8f-11e5-822b-a665a665186f.png)

**Comment by hlmerscher** [comment]
Eu curti, ficou bem legal assim. Só acho que tem que definir um tamanho fixo para a caixinha com a imagem, para o nome não interferir no espaçamento lateral, para não ficar igual ficou ali entre o seu avatar e o do @jvrmaia. Na real, eu nem sei se precisa exibir o nome ali, assim direto. Por mim acho que eu colocaria o nome do alt da tag img. Quem quiser ver o nome é só posicionar o mouse na imagem.

O que acham?

**Comment by jvrmaia** [comment]
:+1:

**Comment by m3nd3s** [comment]
@hlmerscher você disse está dizido! Vou fazer a alteração, fazer os testes e enviar o PR ainda hj :wink:

**Comment by hlmerscher** [comment]
\o/

**Comment by hlmerscher** [comment]
Fechando.

Feito pelo @m3nd3s https://github.com/hlmerscher/dojo-onde/pull/16
