### ISSUE TITLE
Limitar quantidade de participantes em um dojo

### ISSUE THREAD

**Issue by hlmerscher** [hlmerscher/dojo-onde#15]
Definir uma quantidade de participantes no dojo e limitar a participação de acordo com a quantidade registrada. Muito útil quando o local a ser realizado não comporta muitos participantes.

**Comment by m3nd3s** [comment]
Pessoal, vou pegar esse pra fazer também :wink:. Vou pensar como vai ficar e comentar aqui, daí quem puder/quiser opina se achou bacana mesmo

**Comment by m3nd3s** [comment]
1 ano depois e vou fazê-lo :-D

**Comment by gil27** [comment]
:clap:  :clap:  :clap:
