### ISSUE TITLE
Corrigir login via Github

### ISSUE THREAD

**Issue by m3nd3s** [hlmerscher/dojo-onde#18]
Ao tentar realizar login utilizando a conta do Github está ocorrendo erro de DNS:

![image](https://cloud.githubusercontent.com/assets/287685/19476307/2bf350f6-9517-11e6-8d1e-a9d5eb88c1d6.png)

**Comment by hlmerscher** [comment]
Deve ser a configuração da conta do oauth. Quando migrei para o domínio dojoonde.com.br não verifiquei isso.

**Comment by m3nd3s** [comment]
@hlmerscher com o Facebook também falha.

**Comment by hlmerscher** [comment]
Pronto! Tudo funcionando agora. :smile:
