### ISSUE TITLE
Login com conta do Google

### ISSUE THREAD

**Issue by hlmerscher** [hlmerscher/dojo-onde#19]

**Comment by jaquesdias** [comment]
@hlmerscher tudo certo? Já existe algum token de integração com o google? Se sim, pode me vincular a essa issue?

**Comment by hlmerscher** [comment]
@jaquesdias ainda não, mas você pode criar um de teste e usar no desenvolvimento, depois eu crio um token para produção. É só pegar o token via variável de ambiente que fica facinho facinho :wink:

**Comment by m3nd3s** [comment]
@jaquesdias @hlmerscher vou pegar esse aqui 😉

**Comment by m3nd3s** [comment]
Pessoal, a tela de login vai ficar assim:

![image](https://cloud.githubusercontent.com/assets/287685/19686659/f2d26c50-9aa0-11e6-95af-43547eaddcad.png)
