### ISSUE TITLE
Adicionar URLs amigáveis

### ISSUE THREAD

**Issue by m3nd3s** [hlmerscher/dojo-onde#21]
Hoje os dojos são acessados via ID. Ex. dojoonde.com.br/dojos/1. Adicionar suporte para que as URLs fiquem mais amigáveis, mudando para um formato:

dojoonde.com.br/dojos/1-coding-dojo-de-teste

**Comment by jaquesdias** [comment]
Vou resolver essa issue. 😉

**Comment by m3nd3s** [comment]
@jaquesdias manda bala :v:

**Comment by hlmerscher** [comment]
@jaquesdias pode usar https://github.com/norman/friendly_id

**Comment by jaquesdias** [comment]
@hlmerscher foi mal já tinha feito usando o override do método `to_param`. Mas se preferir posso usar esse `friendly_id`.
