### ISSUE TITLE
Atualizar o tema

### ISSUE THREAD

**Issue by hlmerscher** [hlmerscher/dojo-onde#31]
Atualmente está usando a versão 2 do bootstrap, com um tema diferente.

Atualizar para a versão mais nova do bootstrap, ou usar um outro framework como o foundation.

**Comment by m3nd3s** [comment]
@hlmerscher eu votaria no Twitter Bootstrap por ser mais conhecido :)

**Comment by m3nd3s** [comment]
@possatto aí, quer pegar esse? 😄

**Comment by barbier** [comment]
Ainda há a necessidade de mexer nessa issue?

**Comment by hlmerscher** [comment]
O projeto, na verdade, está abandonado. Essa tag do hacktoberfest é do ano passado ainda :stuck_out_tongue:.
